
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-to-prom-proxy-conf
  namespace: openshift-monitoring
data:
  vm-proxy.conf: |
    server {
      listen       8080;
      listen       [::]:8080;
      location /api/v1/status/config {
        proxy_pass http://vmagent-vmagent:8429/config?authKey=foobar;
      }
      location / {
        proxy_pass http://vmselect-vmcluster:8481/select/0/prometheus/;
      }
    }
